spring.application.name=pathfinder
server.port=${PORT:8080}
app.cors.allowed-origin=${ALLOWED_ORIGINS}
spring.main.lazy-initialization=true

# Database
spring.datasource.url=jdbc:${DATASOURCE_URL}
spring.datasource.username=${DATASOURCE_USERNAME}
spring.datasource.password=${DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1

server.tomcat.threads.max=15
server.tomcat.threads.min-spare=2
server.tomcat.max-connections=50
server.tomcat.accept-count=20

spring.websocket.async-send-timeout=5000

# GraphHopper
graphhopper.osm-file=${OSM_FILE_PATH}
graphhopper.graph-cache=${GRAPH_CACHE_PATH}
graphhopper.datareader.data-access=MMAP

# Logging ? reduce to WARN in prod to cut log buffer overhead
logging.level.root=WARN
logging.level.com.graphhopper=WARN
logging.level.com.map.pathfinder=INFO
logging.level.org.springframework.web=WARN



spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.consumer.group-id=location-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

spring.kafka.consumer.properties.spring.deserializer.key.delegate.class=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer

spring.kafka.consumer.properties.spring.json.trusted.packages=com.map.pathfinder.model
spring.kafka.consumer.properties.spring.json.value.default.type=com.map.pathfinder.model.Location
