spring.application.name=pathfinder

server.port=${PORT:8080}


spring.main.lazy-initialization=false

# Logging
logging.level.root=INFO
logging.level.com.graphhopper=INFO
logging.level.com.lian=DEBUG
logging.level.org.springframework.web=INFO

spring.datasource.url=jdbc:${DATASOURCE_URL}
spring.datasource.username=${DATASOURCE_USERNAME}
spring.datasource.password=${DATASOURCE_PASSWORD}
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=create-drop

graphhopper.osm-file=${OSM_FILE_PATH:src/main/resources/data/telangana-latest.osm.pbf}
graphhopper.graph-cache=${GRAPH_CACHE_PATH:graph-cache}



#spring.kafka.bootstrap-servers=localhost:9092
#spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
#spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
#spring.kafka.consumer.group-id=location-group
#spring.kafka.consumer.auto-offset-reset=earliest
#spring.kafka.consumer.key-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
#spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
#
#spring.kafka.consumer.properties.spring.deserializer.key.delegate.class=org.apache.kafka.common.serialization.StringDeserializer
#spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer
#
#spring.kafka.consumer.properties.spring.json.trusted.packages=com.map.pathfinder.model
#spring.kafka.consumer.properties.spring.json.value.default.type=com.map.pathfinder.model.Location
